// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QP.Entity;

namespace QP.Entity.Migrations
{
    [DbContext(typeof(QPContext))]
    [Migration("20201201115814_AddIndex")]
    partial class AddIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QP.Entity.CategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SeriesTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeriesTypeId");

                    b.ToTable("data_Category");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9458),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(8187),
                            Name = "动作片",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9525),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9501),
                            Name = "喜剧",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9529),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9527),
                            Name = "爱情片",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9532),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9531),
                            Name = "科幻片",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9535),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9534),
                            Name = "恐怖片",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9538),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9537),
                            Name = "剧情片",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9541),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9539),
                            Name = "战争片",
                            SeriesTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9544),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9542),
                            Name = "国产剧",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9547),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9545),
                            Name = "港剧",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9550),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9549),
                            Name = "韩剧",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9553),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9552),
                            Name = "欧美剧",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9556),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9555),
                            Name = "纪录片",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9559),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9557),
                            Name = "微电影",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9562),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9561),
                            Name = "台湾剧",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9565),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9563),
                            Name = "日剧",
                            SeriesTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9568),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9566),
                            Name = "大陆综艺",
                            SeriesTypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9571),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9569),
                            Name = "港台综艺",
                            SeriesTypeId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9574),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9572),
                            Name = "日韩综艺",
                            SeriesTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9577),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9575),
                            Name = "欧美综艺",
                            SeriesTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9580),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9578),
                            Name = "国产动漫",
                            SeriesTypeId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9583),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9581),
                            Name = "日韩动漫",
                            SeriesTypeId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9586),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9584),
                            Name = "欧美动漫",
                            SeriesTypeId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9589),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9587),
                            Name = "港台动漫",
                            SeriesTypeId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9592),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 628, DateTimeKind.Local).AddTicks(9591),
                            Name = "其他",
                            SeriesTypeId = 4
                        });
                });

            modelBuilder.Entity("QP.Entity.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.HasKey("Id");

                    b.ToTable("data_message");
                });

            modelBuilder.Entity("QP.Entity.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("Link")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("data_Resource");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 622, DateTimeKind.Local).AddTicks(3536),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 622, DateTimeKind.Local).AddTicks(2097),
                            Link = "http://api.iokzy.com/",
                            Name = "稳定"
                        },
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 622, DateTimeKind.Local).AddTicks(3594),
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 622, DateTimeKind.Local).AddTicks(3570),
                            Link = "http://www.zuidazy4.net/",
                            Name = "高清"
                        });
                });

            modelBuilder.Entity("QP.Entity.SeriesType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("En")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("data_Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            En = "dianying",
                            Icon = "icon_1.png",
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 617, DateTimeKind.Local).AddTicks(5557),
                            Name = "电影"
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 619, DateTimeKind.Local).AddTicks(5556),
                            En = "dianshiju",
                            Icon = "icon_2.png",
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 619, DateTimeKind.Local).AddTicks(5483),
                            Name = "电视剧"
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 619, DateTimeKind.Local).AddTicks(6208),
                            En = "zongyi",
                            Icon = "icon_3.png",
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 619, DateTimeKind.Local).AddTicks(6200),
                            Name = "综艺"
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2020, 12, 1, 19, 58, 13, 619, DateTimeKind.Local).AddTicks(6212),
                            En = "donghua",
                            Icon = "icon_4.png",
                            IsDelete = false,
                            LastModificationTime = new DateTime(2020, 12, 1, 19, 58, 13, 619, DateTimeKind.Local).AddTicks(6210),
                            Name = "动画"
                        });
                });

            modelBuilder.Entity("QP.Entity.VideoBasicInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actor")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Alias")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AreaName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryTypeNames")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("Describes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Dierctor")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("En")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<float>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(8f);

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SeriesTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Actor");

                    b.HasIndex("CategoryTypeId");

                    b.HasIndex("Dierctor");

                    b.HasIndex("En");

                    b.HasIndex("Name");

                    b.HasIndex("Year");

                    b.ToTable("Vod_BasicInfo");
                });

            modelBuilder.Entity("QP.Entity.VideoPlayInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BasicInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Kuyun")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime")
                        .HasMaxLength(0);

                    b.Property<string>("M3u8")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mp4")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("VodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicInfoId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Vod_PlayInfo");
                });

            modelBuilder.Entity("QP.Entity.CategoryType", b =>
                {
                    b.HasOne("QP.Entity.SeriesType", "SeriesType")
                        .WithMany()
                        .HasForeignKey("SeriesTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QP.Entity.VideoBasicInfo", b =>
                {
                    b.HasOne("QP.Entity.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("QP.Entity.VideoPlayInfo", b =>
                {
                    b.HasOne("QP.Entity.VideoBasicInfo", "VideoBasicInfo")
                        .WithMany()
                        .HasForeignKey("BasicInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QP.Entity.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
